#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE_APP_DIR="$ROOT_DIR/site-app"

DROPLET_HOST="${DROPLET_HOST:-root@142.93.159.175}"
REMOTE_WEB_ROOT="${REMOTE_WEB_ROOT:-/var/www/6529vpn}"
PUBLIC_SITE_URL="${PUBLIC_SITE_URL:-https://6529vpn.io}"

VITE_CHAIN="${VITE_CHAIN:-mainnet}"
VITE_SESSION_MANAGER="${VITE_SESSION_MANAGER:-0xb644c990c884911670adc422719243D9F76Df0d6}"
VITE_SUBSCRIPTION_MANAGER="${VITE_SUBSCRIPTION_MANAGER:-0xEb54c8604b7EEADE804d121BD8f158A006827882}"
VITE_NODE_REGISTRY="${VITE_NODE_REGISTRY:-0x1Fd64c16c745e373428068eB52AA73525576B594}"
VITE_ENABLE_ANON_VPN="${VITE_ENABLE_ANON_VPN:-false}"
VITE_ENABLE_ANON_VPN_DEV_REGISTRATION="${VITE_ENABLE_ANON_VPN_DEV_REGISTRATION:-false}"
VITE_ZK_API_URL="${VITE_ZK_API_URL:-}"
VITE_ZK_ARTIFACT_BASE_URL="${VITE_ZK_ARTIFACT_BASE_URL:-}"
VITE_GATEWAY_PROXY_TARGET="${VITE_GATEWAY_PROXY_TARGET:-}"
VITE_GATEWAY_PUBLIC_TARGET="${VITE_GATEWAY_PUBLIC_TARGET:-}"
INSTALL_DEPS="${INSTALL_DEPS:-1}"

if [[ "$VITE_ENABLE_ANON_VPN" == "true" && -z "$VITE_ZK_API_URL" ]]; then
  echo "VITE_ZK_API_URL is required when VITE_ENABLE_ANON_VPN=true" >&2
  exit 1
fi

TMP_ENV=""
BACKUP_ENV=""
cleanup() {
  rm -f "$TMP_ENV"
  if [[ -n "$BACKUP_ENV" && -f "$BACKUP_ENV" ]]; then
    mv "$BACKUP_ENV" "$SITE_APP_DIR/.env.production.local"
  else
    rm -f "$SITE_APP_DIR/.env.production.local"
  fi
}
trap cleanup EXIT

if [[ -f "$SITE_APP_DIR/.env.production.local" ]]; then
  BACKUP_ENV="$SITE_APP_DIR/.env.production.local.codexbak"
  mv "$SITE_APP_DIR/.env.production.local" "$BACKUP_ENV"
fi

TMP_ENV="$SITE_APP_DIR/.env.production.local"
cat >"$TMP_ENV" <<EOF
VITE_CHAIN=$VITE_CHAIN
VITE_SESSION_MANAGER=$VITE_SESSION_MANAGER
VITE_SUBSCRIPTION_MANAGER=$VITE_SUBSCRIPTION_MANAGER
VITE_NODE_REGISTRY=$VITE_NODE_REGISTRY
VITE_ENABLE_ANON_VPN=$VITE_ENABLE_ANON_VPN
VITE_ENABLE_ANON_VPN_DEV_REGISTRATION=$VITE_ENABLE_ANON_VPN_DEV_REGISTRATION
EOF

if [[ -n "$VITE_ZK_API_URL" ]]; then
  printf 'VITE_ZK_API_URL=%s\n' "$VITE_ZK_API_URL" >>"$TMP_ENV"
fi
if [[ -n "$VITE_ZK_ARTIFACT_BASE_URL" ]]; then
  printf 'VITE_ZK_ARTIFACT_BASE_URL=%s\n' "$VITE_ZK_ARTIFACT_BASE_URL" >>"$TMP_ENV"
fi
if [[ -n "$VITE_GATEWAY_PROXY_TARGET" ]]; then
  printf 'VITE_GATEWAY_PROXY_TARGET=%s\n' "$VITE_GATEWAY_PROXY_TARGET" >>"$TMP_ENV"
fi
if [[ -n "$VITE_GATEWAY_PUBLIC_TARGET" ]]; then
  printf 'VITE_GATEWAY_PUBLIC_TARGET=%s\n' "$VITE_GATEWAY_PUBLIC_TARGET" >>"$TMP_ENV"
fi

cd "$SITE_APP_DIR"
if [[ "$INSTALL_DEPS" == "1" ]]; then
  npm ci
fi
npm run build

rsync -az --delete "$SITE_APP_DIR/dist/" "$DROPLET_HOST:$REMOTE_WEB_ROOT/"

echo "Published frontend to $DROPLET_HOST:$REMOTE_WEB_ROOT"
curl -fsS "$PUBLIC_SITE_URL" | grep -oP 'src="\K/assets/[^"]+\.js' | head -n1
